In [48]:
import numpy as np

# Opgave 1
Her kan man bruge arange() der genererer en array i forhold til en range.

In [49]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Her specificerer man float:

In [50]:
np.arange(1,11,1,float)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [51]:
(np.arange(1,11).dtype,np.arange(1,11,1,float).dtype)

(dtype('int64'), dtype('float64'))

# Opgave 2

Her kan man bruge zeros()

In [52]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

Her kan man bruge ones()

In [53]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

Her kan man bruge arange med en range på 1-1000

In [54]:
np.arange(1,1000)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

# Opgave 3

In [58]:
np.array([2,3.2,5.5,-6.4,-2.2,2.4])

array([ 2. ,  3.2,  5.5, -6.4, -2.2,  2.4])

In [59]:
a = np.array([2,3.2,5.5,-6.4,-2.2,2.4])
(a[1],a.dtype)

(3.2, dtype('float64'))

In [61]:
np.array([2,3.2,5.5,-6.4,-2.2,2.4])[1:4]

array([ 3.2,  5.5, -6.4])

# Opgave 4

In [62]:
np.matrix([[2, 3.2, 5.5, -6.4, -2.2, 2.4],
[1, 22, 4, 0.1, 5.3, -9],
[3, 1, 2.1, 21, 1.1, -2]])

matrix([[ 2. ,  3.2,  5.5, -6.4, -2.2,  2.4],
        [ 1. , 22. ,  4. ,  0.1,  5.3, -9. ],
        [ 3. ,  1. ,  2.1, 21. ,  1.1, -2. ]])

In [65]:
a = np.matrix([[2, 3.2, 5.5, -6.4, -2.2, 2.4],
[1, 22, 4, 0.1, 5.3, -9],
[3, 1, 2.1, 21, 1.1, -2]])
a[:,3]

matrix([[-6.4],
        [ 0.1],
        [21. ]])

In [68]:
a = np.matrix([[2, 3.2, 5.5, -6.4, -2.2, 2.4],
[1, 22, 4, 0.1, 5.3, -9],
[3, 1, 2.1, 21, 1.1, -2]])
a[-2:,0:4]

matrix([[ 1. , 22. ,  4. ,  0.1],
        [ 3. ,  1. ,  2.1, 21. ]])